name: Docode自动签到

on:
  workflow_dispatch:  # 支持手动点按钮运行
  schedule:
    - cron: '0 1,2 * * *' # UTC时间，对应北京时间早上1点执行，可自行修改
      timezone: Asia/Shanghai
jobs:
  checkin_job:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 安装依赖
        run: pip install requests

      - name: 运行签到脚本
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          CHECKIN_COOKIE: ${{ secrets.CHECKIN_COOKIE }}
          NEW_API_USER: ${{ secrets.NEW_API_USER }}
        run: python Signin.py
